on: [push, pull_request, release]
name: Test
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php: [ '8.1' ]
        composer-options: [ '', '--prefer-lowest' ]
        composer-versions: [ 'composer:v2' ]
      fail-fast: true
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ matrix.composer-versions }}
          extensions: xdebug, mbstring, posix
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}
      - name: Set git variables
        run: |
          git config --global user.email "git@cben.co"
          git config --global user.name "Christian Rodriguez Benthake"
      - name: Run grumphp
        if: matrix.php != '8.1'
        run: php .Build/bin/grumphp run --no-interaction
      - name: Run phpstan 
        if: matrix.php != '8.1'
        run: php .Build/bin/phpstan